
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

working_directory = "development"

shell = { program = "/opt/homebrew/bin/fish", args = ["-l"] }

[scrolling]
history = 50000

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"
