format = """
$username\
$hostname\
$battery\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$package\
$dotnet\
$golang\
$nodejs\
$java\
$rust\
$ruby\
$terraform\
$nix_shell\
$conda\
$memory_usage\
$aws\
$kubernetes\
$env_var\
$cmd_duration\
$line_break\
$jobs\
$time\
$character"""

[package]
disabled = true

[kubernetes]
disabled = false

[python]
disabled = true

[aws]
disabled = true

[ruby]
disabled = true

[nodejs]
disabled = true

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[character]
error_symbol = "[✗](bold red)"
